### ISSUE TITLE
Incorrect integrals for PieceWiseLinFunc (and possibly DiscreteFunc too)

### ISSUE THREAD

**Issue by jonathanjouty** [mariomulansky/PySpike#37] opened 2018-07-21 15:02 UTC
Didn't think to have a look at the other function classes, but seems to be similar issues as with #33, that it doesn't deal well with certain edge cases.

**Comment by mariomulansky** [comment] 2018-07-22 00:53
PieceWise Linear likely has a similar issue. For DiscreteFunction, an integral between "support points" doesn't really make sense, and should probably just return 0. However, I'm not sure what the code does right now, worth having a look :)

**Comment by mariomulansky** [comment] 2018-09-19 18:04
Closed as duplicate of https://github.com/mariomulansky/PySpike/issues/38

**Closed** 2018-09-19 18:03 UTC
